package dependencies

object LibVersions {
  const val androidDesugarJdk = "2.1.4"
  const val androidGradle = "8.7.3"
  const val androidJUnit5 = "1.9.3.0"
  const val androidMaterial = "1.12.0"
  const val androidxActivityCompose = "1.9.3"
  const val androidxAnnotation = "1.9.1"
  const val androidxAppcompat = "1.7.0"
  const val androidxCompose = "1.7.6"
  const val androidxConstraintLayout = "2.2.0"
  const val androidxConstraintLayoutCompose = "1.1.0"
  const val androidxCore = "1.15.0"
  const val androidxDatastore = "1.1.1"
  const val androidxHilt = "2.51.1"
  const val androidxHiltNavigation = "1.2.0"
  const val androidxLifecycle = "2.8.7"
  const val androidxNavigation = "2.8.5"
  const val androidxPreference = "1.2.1"
  const val androidxRoom = "2.6.1"
  const val androidxTestEspresso = "3.6.1"
  const val androidxTestJunit = "1.2.1"
  const val appcenterPlugin = "1.3.0"
  const val cappuccinoGradle = "0.9.0"
  const val coil = "2.5.0"
  const val dagger = "2.52"
  const val firebase = "33.7.0"
  const val firebaseCrashlyticsGradle = "3.0.2"
  const val foundationAndroid = "1.7.6"
  const val gmsPlugin = "4.4.2"
  const val googleServices = "4.4.2"
  const val gradleVersions = "0.47.0"
  const val junit = "4.13.2"
  const val junit5 = "5.10.0"
  const val kotest = "5.9.1"
  const val kotlin = "2.1.0"
  const val kotlinxCoroutines = "1.8.1"
  const val ksp = "2.1.0-1.0.29"
  const val media3Exoplayer = "1.5.1"
  const val mockk = "1.13.5"
  const val navigationFragmentKtx = "2.8.5"
  const val navigationUiKtx = "2.8.5"
  const val okhttp = "4.12.0"
  const val paperwork = "1.2.7"
  const val playPublisherGradle = "3.8.1"
  const val truth = "1.4.2"
  const val turbine = "1.1.0"
  const val kotlinVersion = "2.0.20"
  const val media3Transformer = "1.5.1"
}

object PluginVersions {
  const val androidGradlePlugin = "8.7.3"
  const val kotlin = "2.1.0"
}
